import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// importing Navbar, which is a router here for every pages on application
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Routing using Navbar */}
        <Navbar />
        {children}
      </body>
    </html>
  );
}
